apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge
spec:
  replicas: 3
  selector:
    matchLabels:
      app: edge
  template:
    metadata:
      labels:
        app: edge
    spec:
      containers:
        - name: edge
          image: docker.io/theblackengineer/edge:0.0.0
          ports:
            - containerPort: 9091
          resources:
            limits:
              cpu: "1"
              memory: "200Mi"
            requests:
              cpu: "500m"
              memory: "100Mi"

          volumeMounts:
            - name: edge-config-volume
              mountPath: /data/edge-config
            - name: keycloak-config-volume
              mountPath: /data/keycloak-config
            - name: edge-secret-volume
              mountPath: /secret/edge-secret
            - name: keycloak-secret-volume
              mountPath: /secret/keycloak-secret

      volumes:
        - name: edge-config-volume
          configMap:
            name: edge-config
        - name: edge-config-volume
          configMap:
            name: keycloak-config
        - name: edge-secret-volume
          secret:
            secretName: edge-secret        
        - name: keycloak-secret-volume
          secret:
            secretName: keycloak-secret
              





