server:
  port: 9090
  netty:
    connection-timeout: 3000
  error:
    whitelabel:
      enabled: false


spring:
  data:
    mongodb:
      uri: localhost:27017
      database: propertydatabase







