# common environment configuration
server:
  port: 9090
  shutdown: graceful

spring:
  application:
    name: PropertyApplication

# development environment configuration
  profile: dev
  data:
    mongo:
      host: localhost
      port: 27017
      database: PropertyDatabase

# staging environment configuration
---
  profile: staging
  data:
    mongo:
      host: localhost
      port: 27017
      database: PropertyDatabase

# production environment configuration
---
  profile: production
  data:
  mongo:
    host: property-mongodb-service
    port: 27017
    database: PropertyDatabase
