apiVersion: v1
kind: Service
metadata:
  name: keycloak-mongodb-service
spec:
  selector:
    app: keycloak-mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  clusterIP: None
