apiVersion: apps/v1
kind: Deployment
metadata:
  name: property-service
  label:
    app: property-service
spec:
  selector:
    matchLabels:
      app: property-service
  template:
    metadata:
      labels:
        app: property-service
    spec:
      containers:
        - name: property-service
          image: property-service
          imagePullPolicy: ifNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]
          ports:
            - containerPort: 9091
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: SPRING_PROFILES_ACTIVE
              value: testdata
          notcomplete:
          volumeMounts:
            - name: property-config-volume
              mountPath: ../kubernetes
      volumes:
        - name: property-config-volume
          configMaps:
            name: property-config



