apiVersion: v1
kind: Service
metadata:
  name: property-mongodb-service
spec:
  selector:
    app: property-mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  clusterIP: None
