server:
  port: 9091
  shutdown: graceful
  error:
    include-message: always
    ssl:
      enabled: false

  data:
    mongo:
      host: localhost
      port: 27018
      database: EdgeDatabase


logging:
  level:
    org.springframework.security: DEBUG


scheme: http
origins: http://localhost:8888
keycloak-port: 8888
keycloak-issuer: http://localhost:8888/realms/houseowner

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8888/realms/houseowner
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8888/realms/houseowner
          keycloak-client:
            client-id: EdgeApplication
            #client-secret: [ CLIENT_SECRET ] # Replace with your Keycloak client secret
            #scope: [ SCOPE1, SCOPE2, ... ] # Replace with the required scopes for your application (comma-separated list)
            scope: openid,profile,email,resource.read

  application:
    name: Edge-Application-Service


spring-addons:
  issuers:
    - uri: http://localhost:8888/realms/houseowner
      username-json-path: $.preferred_username
      claims:
        - jsonPath: $.realm_access.roles
        - jsonPath: $.resource_access.*.roles

realm: houseowner
keycloak:
  server:
    url: http://localhost:8888


twilio:
  account_sid: AC8797b8b123d9e5cbe4892b54c51083d2
  auth_token: 72fad21b66af949877a5914bbb7f3dd
  trial_number: +18786458537


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
    preferIpAddress: true

---
scheme: https
keycloak-port: 9999

server:
  ssl:
    enabled: true

spring:
  config:
    activate:
      on-profile: ssl

