apiVersion: v1

kind: Service

metadata:
  name: property-service
  labels:
    app: property-service

spec:
  type: ClusterIP
  selector:
    app: property-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9091