server:
  port: 9094
  shutdown: graceful
  error:
    include-message: always
    ssl:
      enabled: false


logging:
  level:
    org.springframework.security: DEBUG


spring:
  application:
    name: OTP-Data-Service

  data:
    mongo:
      host: localhost
      port: 27018
      database: OTPDatabase

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
    preferIpAddress: true

